# Generated by Django 5.1 on 2024-08-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0003_category_alter_labeledimage_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default="Category", max_length=255),
        ),
    ]
