# Generated by Django 5.1 on 2024-08-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0004_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="Category", max_length=100),
        ),
    ]
